# Generated by Django 2.2.3 on 2019-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('E', 'Education'), ('L', 'Location'), ('W', 'Work')], max_length=1)),
                ('title', models.CharField(max_length=128)),
                ('title_prefix', models.CharField(max_length=16)),
                ('subtitle', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
