# Generated by Django 2.2.3 on 2019-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_remove_event_title_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('E', 'Education'), ('L', 'Location'), ('W', 'Work'), ('R', 'Recreation')], max_length=1),
        ),
    ]
