# Generated by Django 2.2.3 on 2019-07-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_auto_20190730_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Location'), (1, 'Education'), (2, 'Work'), (3, 'Recreation')]),
        ),
    ]
