# Generated by Django 2.2.3 on 2019-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_auto_20190730_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
