# Generated by Django 3.2.8 on 2021-10-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_auto_20211014_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
