# Generated by Django 3.2.8 on 2021-10-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_auto_20211014_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
