# Generated by Django 3.2.8 on 2021-10-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_alter_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
