# Generated by Django 3.2.8 on 2021-10-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_alter_event_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
    ]
